#!/bin/bash

run_function0 (){

if [[ -f "board.txt" ]]; then
	sed -i 's/net.ifnames=0/net.ifnames=0 processor.max_cstate=1 isolcpus=2,3/g' board.txt
fi
}
run_function1 (){

# remove sudo no password
rm -f /p2/etc/sudoers.d/010_${USERNAME}-nopasswd
echo "run_function 1 completed" 
}

run_function2 (){
# Install Linuxcnc dependencies
#apt-get install -y xdg-utils python3-serial python3-yapps librsvg2-dev python3-pil python3-pil.imagetk python3 libboost-python1.74.0 libboost-python1.74.0-py311 libc6 libcairo2 libedit2 libepoxy0 libgcc-s1 libglib2.0-0 libgpiod2 libgtk-3-0 libgtk2.0-0 libmodbus5  libpango-1.0-0 libpangocairo-1.0-0 libpython3.11 libstdc++6 libtirpc3 libtk8.6 libudev1 libusb-1.0-0 libx11-6 libxinerama1 libxmu6 libudev-dev iptables blt mesa-utils python3-tk python3-numpy python3-cairo python3-gi-cairo python3-opengl python3-configobj python3-xlib libgtksourceview-3.0-dev tcl8.6 tk8.6 bwidget tclreadline tclx python3-pyqt5 python3-pyqt5.qsci python3-pyqt5.qtsvg python3-pyqt5.qtopengl python3-opencv python3-dbus python3-espeak python3-dbus.mainloop.pyqt5 python3-pyqt5.qtwebengine python3-pyqt5.qtwebkit espeak-ng pyqt5-dev-tools gstreamer1.0-tools espeak sound-theme-freedesktop python3-poppler-qt5 procps psmisc udev

# Get the Linuxcnc Debs

echo "Installing linuxcnc repository" 
mkdir -p /tmp/linuxcnc/
cd /tmp/linuxcnc/
gpg --homedir /tmp/linuxcnc/ --keyserver hkp://keyserver.ubuntu.com --recv-key 3cb9fd148f374fef
gpg --homedir /tmp/linuxcnc/ --export 'EMC Archive Signing Key' | tee /usr/share/keyrings/linuxcnc.gpg > /dev/null
echo 'deleting temp files'

# Install companion repositories. NOTE: QTPYVCP does not support the raspberry pi.

echo "Install ethercat repository"
mkdir -p /usr/local/share/keyrings/
wget -O- https://build.opensuse.org/projects/science:EtherLab/signing_keys/download?kind=gpg | gpg --dearmor | dd of=/etc/apt/trusted.gpg.d/science_EtherLab.gpg
tee -a /etc/apt/sources.list.d/ighvh.sources > /dev/null <<EOT
Types: deb
Signed-By: /etc/apt/trusted.gpg.d/science_EtherLab.gpg
Suites: ./
URIs: http://download.opensuse.org/repositories/science:/EtherLab/Debian_12/
EOT

echo 'Updating apt repository list'
echo deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/linuxcnc.gpg] https://www.linuxcnc.org/ bookworm base 2.9-uspace | tee /etc/apt/sources.list.d/linuxcnc.list > /dev/null
echo deb-src [arch=amd64,arm64 signed-by=/usr/share/keyrings/linuxcnc.gpg] https://www.linuxcnc.org/ bookworm base 2.9-uspace | tee -a /etc/apt/sources.list.d/linuxcnc.list > /dev/null

tee -a /etc/apt/preferences.d/99linuxcnc-uspace.pref > /dev/null <<EOT
package: linuxcnc-uspace
pin: release o=https://www.linuxcnc.org/ bookworm base 2.9-uspace 
Pin-Priority: 500

package: linuxcnc-uspace-dev
pin: release o=https://www.linuxcnc.org/ bookworm base 2.9-uspace 
Pin-Priority: 500

package: linuxcnc-uspace-doc-en
pin: release o=https://www.linuxcnc.org/ bookworm base 2.9-uspace
Pin-Priority: 500

package: linuxcnc-uspace-doc-de
pin: release o=https://www.linuxcnc.org/ bookworm base 2.9-uspace
Pin-Priority: 500

package: linuxcnc-uspace-doc-es
pin: release o=https://www.linuxcnc.org/ bookworm base 2.9-uspace
Pin-Priority: 500

package: linuxcnc-uspace-doc-fr
pin: release o=https://www.linuxcnc.org/ bookworm base 2.9-uspace 2.9-rt
Pin-Priority: 500

package: linuxcnc-uspace-doc-zh-cn
pin: release o=https://www.linuxcnc.org/ bookworm base 2.9-uspace 2.9-rt
Pin-Priority: 500
EOT


echo 'Updating APT index'
apt-get update
echo 'Installing LinuxCNC'
apt-get install -y linuxcnc-uspace linuxcnc-uspace-dev mesaflash

echo 'Installing Flexi dependencies and tools'
apt-get install -y git pigpio-tools stm32flash qtbase5-dev qt5-qmake libmodbus-dev python3-gst-1.0 cutecom libusb-1.0-0-dev

echo 'Building vfdmod'
cd /tmp
git clone --depth 1 https://github.com/mikemacwillie/vfdmod.git
mkdir vfdmod/build
cd vfdmod/build
qmake ../vfdmod.pro
make
cp vfdmod /usr/bin

echo 'Cloning the remora-flexi hal repo and building flexi component'
cd /home/${USERNAME}
git clone https://github.com/Expatria-Technologies/remora-flexi-hal.git remora-flexi-hal
cd remora-flexi-hal/LinuxCNC/Components/Flexi/
halcompile --install flexi.c
mkdir /home/${USERNAME}/linuxcnc
mkdir /home/${USERNAME}/linuxcnc/configs
mkdir /home/${USERNAME}/linuxcnc/nc_files
cp -av /home/${USERNAME}/remora-flexi-hal/LinuxCNC/ConfigSamples/flexi-hal /home/${USERNAME}/linuxcnc/configs
if [ $BOARD == "bcm2711" ]; then
   echo "Reconfiguring vfdmod serial port for Pi 4"
   sed -i 's/AMA2/AMA3/' /home/${USERNAME}/linuxcnc/configs/flexi-hal/vfdmod.ini
fi


echo 'Cloning the Remora repo and building remora-eth component for use with uFlexiNet'
cd /tmp
git clone --depth 1 https://github.com/Expatria-Technologies/Remora.git
cd Remora/LinuxCNC/Components/Remora-eth
halcompile --install remora-eth.c

echo 'Cloning the linuxcnc_configs repo and grabbing the uFlexiNet reference config'
cd /tmp
git clone --depth 1 https://github.com/Expatria-Technologies/linuxcnc_configs.git
cp -av /tmp/linuxcnc_configs/flexi-hal-uFlexiNet-XYZ /home/${USERNAME}/linuxcnc/configs/uFlexiNet
if [ $BOARD == "bcm2712" ]; then
   echo "Configuring for Pi 5"
   sed -i 's/AMA1/AMA2/' /home/${USERNAME}/linuxcnc/configs/uFlexiNet/vfdmod.ini
elif [ $BOARD == "bcm2711" ]; then
   echo "Configuring for Pi 4"
   sed -i 's/AMA1/AMA3/' /home/${USERNAME}/linuxcnc/configs/uFlexiNet/vfdmod.ini
   sed -i 's/AMA2/AMA3/' /home/${USERNAME}/linuxcnc/configs/uFlexiNet/vfdmod.ini
fi


echo 'Cloning the Flexi-Ninja repo and building flexi-ninja components'
cd /home/${USERNAME}
git clone https://github.com/Expatria-Technologies/Flexi-Ninja.git flexi-ninja
cd flexi-ninja/hal-driver/
./make_symlinks.sh
./install.sh
#May need these later if we reorder things. Created in the remora-flexi-hal step right now.
#mkdir /home/${USERNAME}/linuxcnc
#mkdir /home/${USERNAME}/linuxcnc/configs
#mkdir /home/${USERNAME}/linuxcnc/nc_files
cp -av /home/${USERNAME}/flexi-ninja/config-samples/flexi-ninja /home/${USERNAME}/linuxcnc/configs
cp -av /home/${USERNAME}/flexi-ninja/config-samples/flexi-ninja-eth /home/${USERNAME}/linuxcnc/configs
if [ $BOARD == "bcm2711" ]; then
   echo "Reconfiguring vfdmod serial port for Pi 4"
   sed -i 's/AMA2/AMA3/' /home/${USERNAME}/linuxcnc/configs/flexi-ninja/vfdmod.ini
   sed -i 's/AMA2/AMA3/' /home/${USERNAME}/linuxcnc/configs/flexi-ninja-eth/vfdmod.ini
fi

echo 'Populating the firmware directories'
mkdir -p /home/${USERNAME}/firmware/flexi-ninja /home/${USERNAME}/firmware/flexgpio_bootloader /home/${USERNAME}/firmware/remora-flexi-hal
#Flexi-Ninja SPI
curl -fsSL -o /home/${USERNAME}/firmware/flexi-ninja/Flexi-Ninja_FlexiHAL_2350_SPI.elf https://github.com/Expatria-Technologies/flexi-ninja/releases/latest/download/Flexi-Ninja_FlexiHAL_2350_SPI.elf
curl -fsS https://api.github.com/repos/Expatria-Technologies/flexi-ninja/releases/latest | awk -F'"' '/"tag_name":/{t=$4} t && /"updated_at":/{print t; print $4; exit}' > /home/${USERNAME}/firmware/flexi-ninja/Flexi-Ninja_FlexiHAL_2350_SPI.elf.version || true
#Flexi-Ninja Ethernet
curl -fsSL -o /home/${USERNAME}/firmware/flexi-ninja/Flexi-Ninja_FlexiHAL_2350_W5500.elf https://github.com/Expatria-Technologies/flexi-ninja/releases/latest/download/Flexi-Ninja_FlexiHAL_2350_W5500.elf
curl -fsS https://api.github.com/repos/Expatria-Technologies/flexi-ninja/releases/latest | awk -F'"' '/"tag_name":/{t=$4} t && /"updated_at":/{print t; print $4; exit}' > /home/${USERNAME}/firmware/flexi-ninja/Flexi-Ninja_FlexiHAL_2350_W5500.elf.version || true
# FlexGPIO Bootloader
curl -fsSL -o /home/${USERNAME}/firmware/flexgpio_bootloader/FlexGPIO_bootloader.elf https://github.com/Expatria-Technologies/FlexGPIO_Bootloader/releases/latest/download/FlexGPIO_bootloader.elf
curl -fsS https://api.github.com/repos/Expatria-Technologies/FlexGPIO_Bootloader/releases/latest | awk -F'"' '/"tag_name":/{t=$4} t && /"updated_at":/{print t; print $4; exit}' > /home/${USERNAME}/firmware/flexgpio_bootloader/FlexGPIO_bootloader.elf.version || true
# Remora Flex-HAL
curl -fsSL -o /home/${USERNAME}/firmware/remora-flexi-hal/Remora-Flex-Hal_v1.0.0.bin https://github.com/Expatria-Technologies/remora-flexi-hal/releases/latest/download/Remora-Flex-Hal_v1.0.0.bin
curl -fsS https://api.github.com/repos/Expatria-Technologies/remora-flexi-hal/releases/latest | awk -F'"' '/"tag_name":/{t=$4} t && /"updated_at":/{print t; print $4; exit}' > /home/${USERNAME}/firmware/remora-flexi-hal/Remora-Flex-Hal_v1.0.0.bin.version || true


echo 'Installing RPi OpenOCD for board flashing'
cd /tmp/
git clone --depth 1 --shallow-submodules https://github.com/raspberrypi/openocd.git --recurse-submodules
cd openocd
./bootstrap
./configure --enable-internal-jimtcl --enable-sysfsgpio --enable-bcm2835gpio
make -j$(nproc)
sudo make install


echo 'Cloning the upstream Remora repo and installing the default remora-spi and remora-eth-3.0 components for non-Expatria boards'
cd /tmp
git clone --depth 1 https://github.com/scottalford75/Remora.git Remora-upstream
cd Remora-upstream/LinuxCNC/Components/Remora-spi
halcompile --install remora-spi.c
cd /tmp/Remora-upstream/LinuxCNC/Components/Remora-eth
halcompile --install remora-eth-3.0.c
cd /tmp/Remora-upstream/LinuxCNC/Components/PRUencoder
halcompile --install PRUencoder.c


echo 'Copying ngcgui library to config dir'
cp -av /usr/share/linuxcnc/ncfiles/ngcgui_lib /home/${USERNAME}/linuxcnc/


echo 'Enabling auto-login for ${USERNAME} user'
sed -i "s/\#autologin-user=/autologin-user=${USERNAME}/" /etc/lightdm/lightdm.conf

echo 'Disabling display power management and sleep by default'
tee /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml <<EOF
<channel name="xfce4-power-manager" version="1.0">
  <property name="xfce4-power-manager" type="empty">
    <property name="power-button-action" type="empty"/>
    <property name="show-tray-icon" type="bool" value="false"/>
    <property name="blank-on-ac" type="int" value="0"/>
    <property name="dpms-on-ac-sleep" type="uint" value="0"/>
    <property name="dpms-on-ac-off" type="uint" value="0"/>
  </property>
</channel>
EOF

echo 'Cleaning up temp files'
cd /tmp
rm -Rf /tmp/vfdmod
rm -Rf /tmp/Remora
rm -Rf /tmp/Remora-upstream
rm -Rf /tmp/linuxcnc_configs
rm -rf /tmp/linuxcnc
rm -rf /tmp/openocd

# Finished!
echo "Stage 2 done"
}

run_function3 (){
echo "Entering run_function3"	
}

