name: Build Kernel Packages

on:
  workflow_dispatch:
  #push:
    #branches: [ "master" ]
jobs:
  board_matrix:
    strategy:
      matrix:
        board: [bcm2712, bcm2711]
    runs-on: ubuntu-24.04
    environment: Test
    steps:
    - name: Install toolchain
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential curl
            
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: make ccompile

    - name: Build kernel
      run: make commit board=${{ matrix.board }}

    - name: Archive image artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Kernel ${{ matrix.board }}
        path: |
            output/${{ matrix.board }}/*.deb
